name: Sync to Hugging Face hub
on:
  push:
    branches: [Swarm]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Get repo names
        env:
          HF_AUTH_LINK: ${{ secrets.HF_AUTH_LINK }}
        id: get-repo-names
        run: |
          # Make a GET request to get the list of repo names
          response=$(curl -X GET -H "Content-Type: application/json" ${{ secrets.RTDB }}/nodes.json)
          repos=$(echo $response | jq -r '. | to_entries[] | select(.value.HOST_NAME) | (.value.HOST_NAME | sub("yakova-"; "") | sub("\\.hf\\.space"; ""))')

          # Split the repos into an array
          IFS=' ' read -ra repoArray <<< "$repos"

          # Loop through the repoArray
          for repo in "${repoArray[@]}"; do
            # Perform operations on each repo
            git push $HF_AUTH_LINK/$repo Swarm:main
            echo "Processing repo: $repo"
            # Add your desired operations here
          done
