name: Sync to Hugging Face hub
on:
  push:
    branches: [Swarm]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Get repo names
        id: get-repo-names
        run: |
          # Make a GET request to get the list of repo names
            response=$(curl -X GET -H "Content-Type: application/json" ${{ secrets.RTDB }}/repos.json)
          echo "::set-output name=repos::$(echo $response | jq -r '.repos | join(",")')"
      - name: Push changes to repos
        env:
          HF_AUTH_LINK: ${{ secrets.HF_AUTH_LINK }}
        run: |
          # Split the repo names into an array
          IFS=',' read -ra repos <<< "${{ steps.get-repo-names.outputs.repos }}"
          for repo in "${repos[@]}"; do
            git push $HF_AUTH_LINK/$repo Swam:main
          done
